# Import libraries

In [1]:
import sys
import os
import pandas as pd 

sys.path.append(os.path.abspath(".."))

In [2]:
from src.data_loader import load_data

# Load Data 
##### Data Exploring

In [ ]:
df =pd.read_csv( "../data/raw/Customer Transactions.csv")

df.head()

,ACCOUNTNO,TRANSDATE,TRANSACTIONDETAILS,VALUEDATE,WITHDRAWALAMT,DEPOSITAMT,CUSTOMER_AGE,GENDER,DEPENDENT_COUNT,EDUCATION_LEVEL,MARITAL_STATUS,INCOME_CATEGORY,CARD_CATEGORY,MONTHS_ON_BOOK,TOTAL_RELATIONSHIP_COUNT,MONTHS_INACTIVE_12_MON,CONTACTS_COUNT_12_MON,CREDIT_LIMIT,TOTAL_REVOLVING_BAL
0,710481333,12-Jan-18,FDRL/INTERNAL FUND TRANSFE,12-Jan-18,NaN,"500,000.00",50,F,4,High School,Married,Less than $40K,Blue,36,5,3,5,2690.0,1614
1,721107258,12-Jan-18,FDRL/INTERNAL FUND TRANSFE,12-Jan-18,NaN,"500,000.00",45,F,5,Unknown,Unknown,Less than $40K,Blue,37,2,2,2,5465.0,1967
2,798917883,12-Jan-18,FDRL/INTERNAL FUND TRANSFE,12-Jan-18,NaN,"500,000.00",42,F,4,College,Single,Less than $40K,Blue,36,2,3,2,4150.0,2517
3,771575058,12-Jan-18,FDRL/INTERNAL FUND TRANSFE,12-Jan-18,NaN,"500,000.00",45,M,1,Graduate,Married,Less than $40K,Blue,33,4,3,4,2009.0,1795
4,715480983,15-Jan-18,INDO GIBL Indiaforensic STL14011,15-Jan-18,"5,000.00",NaN,55,F,2,College,Single,Less than $40K,Blue,36,5,2,3,5719.0,892

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 116201 entries, 0 to 116200
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ACCOUNTNO                 116201 non-null  int64
 1   TRANSDATE                 116201 non-null  str
 2   TRANSACTIONDETAILS        113702 non-null  str
 3   VALUEDATE                 116201 non-null  str
 4   WITHDRAWALAMT             53549 non-null   str
 5   DEPOSITAMT                62652 non-null   str
 6   CUSTOMER_AGE              116201 non-null  int64
 7   GENDER                    116201 non-null  str
 8   DEPENDENT_COUNT           116201 non-null  int64
 9   EDUCATION_LEVEL           116201 non-null  str
 10  MARITAL_STATUS            116201 non-null  str
 11  INCOME_CATEGORY           116201 non-null  str
 12  CARD_CATEGORY             116201 non-null  str
 13  MONTHS_ON_BOOK            116201 non-null  int64
 14  TOTAL_RELATIONSHIP_COUNT  116201 non-null  int64
 15  MONTHS_INACTIVE_12_MON    116201 non-null  int64
 16  CONTACTS_COUNT_12_MON     116201 non-null  int64
 17  CREDIT_LIMIT              116201 non-null  float64
 18  TOTAL_REVOLVING_BAL       116201 non-null  int64
dtypes: float64(1), int64(8), str(10)
memory usage: 16.8 MB

# Data Preprocessing
#### Ddealing with missing Values

In [64]:
df.isna().sum()

ACCOUNTNO                       0
TRANSDATE                       0
TRANSACTIONDETAILS           2499
VALUEDATE                       0
WITHDRAWALAMT               62652
DEPOSITAMT                  53549
CUSTOMER_AGE                    0
GENDER                          0
DEPENDENT_COUNT                 0
EDUCATION_LEVEL                 0
MARITAL_STATUS                  0
INCOME_CATEGORY                 0
CARD_CATEGORY                   0
MONTHS_ON_BOOK                  0
TOTAL_RELATIONSHIP_COUNT        0
MONTHS_INACTIVE_12_MON          0
CONTACTS_COUNT_12_MON           0
CREDIT_LIMIT                    0
TOTAL_REVOLVING_BAL             0
dtype: int64

In [65]:
df[["WITHDRAWALAMT", "DEPOSITAMT"]].head(20)

   WITHDRAWALAMT  DEPOSITAMT
0            NaN  500,000.00
1            NaN  500,000.00
2            NaN  500,000.00
3            NaN  500,000.00
4       5,000.00         NaN
5     348,200.00         NaN
6     112,900.00         NaN
7     392,251.00         NaN
8     412,300.00         NaN
9     518,375.00         NaN
10    296,450.00         NaN
11           NaN  500,000.00
12           NaN  500,000.00
13    274,600.00         NaN
14    159,725.00         NaN
15     69,000.00         NaN
16    244,350.00         NaN
17    224,800.00         NaN
18           NaN  500,000.00
19           NaN  500,000.00

In [66]:
print("Depo",df["DEPOSITAMT"].isna().sum())
print("with",df["WITHDRAWALAMT"].isna().sum())

Depo 53549
with 62652

In [67]:
# Change the dtype to numeric
df["DEPOSITAMT"] = df["DEPOSITAMT"].astype(str).str.replace(",", "")
df["WITHDRAWALAMT"] = df["WITHDRAWALAMT"].astype(str).str.replace(",", "")
df["DEPOSITAMT"] = pd.to_numeric(df["DEPOSITAMT"], errors="coerce")
df["WITHDRAWALAMT"] = pd.to_numeric(df["WITHDRAWALAMT"], errors="coerce")

In [68]:
df["WITHDRAWALAMT"].dtype

dtype('float64')

In [69]:
# When we have a withdrawal, we don't have a deposit and vice versa. So we can fill the missing values with 0.
df["DEPOSITAMT"] =  df["DEPOSITAMT"].fillna(0)
df["WITHDRAWALAMT"] =  df["WITHDRAWALAMT"].fillna(0)

In [70]:
df[["WITHDRAWALAMT", "DEPOSITAMT"]].head(10)

   WITHDRAWALAMT  DEPOSITAMT
0            0.0    500000.0
1            0.0    500000.0
2            0.0    500000.0
3            0.0    500000.0
4         5000.0         0.0
5       348200.0         0.0
6       112900.0         0.0
7       392251.0         0.0
8       412300.0         0.0
9       518375.0         0.0

#### Convert Date Column to Date Time Type

In [71]:
df["VALUEDATE"]= pd.to_datetime(df["VALUEDATE"])
df["TRANSDATE"]= pd.to_datetime(df["TRANSDATE"])

C:\Users\user\AppData\Local\Temp\ipykernel_14648\3858057769.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["VALUEDATE"]= pd.to_datetime(df["VALUEDATE"])
C:\Users\user\AppData\Local\Temp\ipykernel_14648\3858057769.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["TRANSDATE"]= pd.to_datetime(df["TRANSDATE"])

In [72]:
df.dtypes

ACCOUNTNO                            int64
TRANSDATE                   datetime64[us]
TRANSACTIONDETAILS                     str
VALUEDATE                   datetime64[us]
WITHDRAWALAMT                      float64
DEPOSITAMT                         float64
CUSTOMER_AGE                         int64
GENDER                                 str
DEPENDENT_COUNT                      int64
EDUCATION_LEVEL                        str
MARITAL_STATUS                         str
INCOME_CATEGORY                        str
CARD_CATEGORY                          str
MONTHS_ON_BOOK                       int64
TOTAL_RELATIONSHIP_COUNT             int64
MONTHS_INACTIVE_12_MON               int64
CONTACTS_COUNT_12_MON                int64
CREDIT_LIMIT                       float64
TOTAL_REVOLVING_BAL                  int64
dtype: object

#### Creating Customer Level Aggregation w.r.t Transactions

In [73]:
customer_transactions = df.groupby("ACCOUNTNO").agg(
    total_deposit = ("DEPOSITAMT", "sum"),
    total_withdrawal = ("WITHDRAWALAMT", "sum"),
    average_deposit = ("DEPOSITAMT", "mean"),
    average_withdrawal = ("WITHDRAWALAMT", "mean"),
    transaction_count = ("ACCOUNTNO", "count")
).reset_index()



customer_transactions["net_flow"]= (

    customer_transactions["total_deposit"] - customer_transactions["total_withdrawal"]
)

In [74]:
customer_transactions.columns

Index(['ACCOUNTNO', 'total_deposit', 'total_withdrawal', 'average_deposit',
       'average_withdrawal', 'transaction_count', 'net_flow'],
      dtype='str')

In [75]:
customer_transactions.head()

,ACCOUNTNO,total_deposit,total_withdrawal,average_deposit,average_withdrawal,transaction_count,net_flow
0,708082083,1.200000e+04,0.00,1.200000e+04,0.000000e+00,1,12000.00
1,708083283,3.118584e+07,68970583.09,1.299410e+06,2.873774e+06,24,-37784743.05
2,708084558,1.376231e+08,45033176.38,4.587436e+06,1.501106e+06,30,92589913.91
3,708085458,0.000000e+00,233851.00,0.000000e+00,2.338510e+05,1,-233851.00
4,708098133,3.000000e+05,0.00,3.000000e+05,0.000000e+00,1,300000.00

In [76]:
customer_transactions.shape

(7260, 7)

#### Creating Customer Attribute Table

In [77]:
customer_profile =df.groupby("ACCOUNTNO").first().reset_index()

In [78]:
customer_profile = customer_profile.drop(
    ["TRANSDATE", "VALUEDATE", "TRANSACTIONDETAILS",'WITHDRAWALAMT', 'DEPOSITAMT'],
    axis=1
)

In [79]:
customer_profile.shape

(7260, 14)

In [80]:
customer_profile.head()

,ACCOUNTNO,CUSTOMER_AGE,GENDER,DEPENDENT_COUNT,EDUCATION_LEVEL,MARITAL_STATUS,INCOME_CATEGORY,CARD_CATEGORY,MONTHS_ON_BOOK,TOTAL_RELATIONSHIP_COUNT,MONTHS_INACTIVE_12_MON,CONTACTS_COUNT_12_MON,CREDIT_LIMIT,TOTAL_REVOLVING_BAL
0,708082083,45,F,3,High School,Married,Less than $40K,Blue,36,4,3,3,3544.0,1661
1,708083283,58,M,0,Unknown,Single,$40K - $60K,Blue,45,3,1,3,3421.0,2517
2,708084558,46,M,3,Doctorate,Divorced,$80K - $120K,Blue,38,6,3,3,8258.0,1771
3,708085458,34,F,2,Uneducated,Single,Less than $40K,Blue,24,6,2,2,1438.3,0
4,708098133,32,F,0,Graduate,Married,Less than $40K,Blue,19,6,1,0,2834.0,1418

In [81]:
customer_profile.columns

Index(['ACCOUNTNO', 'CUSTOMER_AGE', 'GENDER', 'DEPENDENT_COUNT',
       'EDUCATION_LEVEL', 'MARITAL_STATUS', 'INCOME_CATEGORY', 'CARD_CATEGORY',
       'MONTHS_ON_BOOK', 'TOTAL_RELATIONSHIP_COUNT', 'MONTHS_INACTIVE_12_MON',
       'CONTACTS_COUNT_12_MON', 'CREDIT_LIMIT', 'TOTAL_REVOLVING_BAL'],
      dtype='str')

#### Creating Customer data frame

In [82]:
# merging the 2 tables on ACCOUNTNO

customer_df = customer_profile.merge(
    customer_transactions,
     on="ACCOUNTNO",
      how="left"
)

this will help in anomaly detection for future because giving behavior along with transaction data for customer will help anomaly model to detect better

In [84]:
print(customer_df.shape)
customer_df.head()

(7260, 20)

,ACCOUNTNO,CUSTOMER_AGE,GENDER,DEPENDENT_COUNT,EDUCATION_LEVEL,MARITAL_STATUS,INCOME_CATEGORY,CARD_CATEGORY,MONTHS_ON_BOOK,TOTAL_RELATIONSHIP_COUNT,MONTHS_INACTIVE_12_MON,CONTACTS_COUNT_12_MON,CREDIT_LIMIT,TOTAL_REVOLVING_BAL,total_deposit,total_withdrawal,average_deposit,average_withdrawal,transaction_count,net_flow
0,708082083,45,F,3,High School,Married,Less than $40K,Blue,36,4,3,3,3544.0,1661,1.200000e+04,0.00,1.200000e+04,0.000000e+00,1,12000.00
1,708083283,58,M,0,Unknown,Single,$40K - $60K,Blue,45,3,1,3,3421.0,2517,3.118584e+07,68970583.09,1.299410e+06,2.873774e+06,24,-37784743.05
2,708084558,46,M,3,Doctorate,Divorced,$80K - $120K,Blue,38,6,3,3,8258.0,1771,1.376231e+08,45033176.38,4.587436e+06,1.501106e+06,30,92589913.91
3,708085458,34,F,2,Uneducated,Single,Less than $40K,Blue,24,6,2,2,1438.3,0,0.000000e+00,233851.00,0.000000e+00,2.338510e+05,1,-233851.00
4,708098133,32,F,0,Graduate,Married,Less than $40K,Blue,19,6,1,0,2834.0,1418,3.000000e+05,0.00,3.000000e+05,0.000000e+00,1,300000.00

In [89]:
customer_df.to_csv("../data/processed/customer_features.csv", index=False)